POST http://localhost:3000/register/
Content-Type:application/json

{
  "username": "richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

POST http://localhost:3000/login/
Content-Type:application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

GET http://localhost:3000/user/tweets/feed/
Authorization: bearer JWT_ACCESS-TOKEN

GET http://localhost:3000/user/following/
Authorization: bearer JWT_ACCESS-TOKEN

GET http://localhost:3000/user/followers/
Authorization: bearer JWT_ACCESS-TOKEN

GET http://localhost:3000/tweets/1/
Authorization: bearer JWT_ACCESS-TOKEN

GET http://localhost:3000/tweets/1/likes/
Authorization: bearer JWT_ACCESS-TOKEN

GET http://localhost:3000/tweets/1/replies/
Authorization: bearer JWT_ACCESS-TOKEN

GET http://localhost:3000/user/tweets/
Authorization: bearer JWT_ACCESS-TOKEN

POST http://localhost:3000/user/tweets/
Authorization: bearer JWT_ACCESS-TOKEN
Content-Type:application/json

{
   "tweet": "The Mornings..."
}

DELETE http://localhost:3000/tweets/14/
Authorization: bearer JWT_ACCESS-TOKEN


